- hosts: localhost
  vars:
    host: "172.16.106.131"
    username: "admin"
    password: "admin"
  tasks:
  - name: Set vip on the fortigate
    connection: local
    fortiosconfig:
      https: False
      action: "set"
      host:  "{{host}}"
      username: "{{username}}"
      password: "{{password}}"
      config: "firewall vip"
      https: True
      ssl_verify: False
      config_parameters:
        name: "1"
        type: static-nat
        dns-mapping-ttl: 0
        ldb-method: static
        extip: 1.1.1.1
        mappedip:
        - range: 10.10.10.10
        extintf: port6
        arp-reply: enable
        protocol: tcp
        extport: 0-65535
        mappedport: 0-65535
