- hosts: localhost
  tasks:
  - name: Register units
    forticare_register_units:
      token: YOUR_TOKEN
      version: 1.0
      registration_units:
        - serial_number: FMG-3K3407400109
          contract_number: ""
          description: Backup device
          asset_group_ids: ""
          replaced_serial_number: ""
          additional_info: "10.1.1.1"
          is_government: false
    register: output
  - debug:
      var: output
  - debug:
      var: output.meta.status_code
  - debug:
      var: output.meta.reason
  - debug:
      var: output.meta.content
  - debug:
      var: output.meta.content.Status
