- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "global"
  tasks:
  - name: system config restore
    fortiosconfig:
     config: "system global"
     action: "set"
     host:  "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom:  "{{ vdom }}"
     https: False
     ssl_verify: False
     config_parameters:
      admin-https-redirect: "disable"
