- hosts: localhost
  tasks:
  - name: Get Assets
    forticare_get_assets:
      token: 9EYZ-YOUR-TOKEN-5NCS
      version: 1.0
      serial_number: FGT%
      expire_before: 2019-01-20T10:11:11-8:00
      page_number: 1