- hosts: localhost
#  strategy: debug
  vars:
   host: "172.16.106.131"
   username: "admin"
   password: "admin"
   vdom: "root"
  tasks:
  - name: delete firewall policy
    fortiosconfig:
     config: "firewall policy"
     action: "delete"
     host: "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom: "{{ vdom }}"
     https: False
     ssl_verify: False
     config_parameters:
       policyid: "1"
       name: "ping"
       action: "accept"
       srcintf: [ {"name": "any"} ]
       dstintf: [{"name":"any"} ]
       srcaddr: [{"name":"all"} ]
       dstaddr: [{"name":"all"}]
       schedule: "always"
       service: [{"name":"HTTPS"}]
       logtraffic: "all"
